### ISSUE TITLE
Hey jake

### ISSUE THREAD

**Issue by joshkmartinez** [jakehamilton/starter-typescript-template#1]
I had no other way you contact you so I am just going to open an issue on your lastest repo.
Could you delete the LHHS Technology github that you made. https://github.com/lagunahills ?
I've created one for the cs club and I dont want people to find the wrong thing.

**Comment by jakehamilton** [comment]
I can do that, but would you rather me give you ownership of the lagunahills one?

**Comment by joshkmartinez** [comment]
Just delete it. I already made a github org a while back. https://github.com/lhhs-cs

Thanks

**Comment by jakehamilton** [comment]
Done!
